/* Hazır destek talepleri (Destek Masası) · seviye 1-5 */
window.PP_TICKETS = [
  /* L1: tek cümle */
  { id: "s-t01", level: 1, category: "printer", subject: "Printer not working", from: { name: "Anna", role: "HR assistant", country: "Germany" },
    body: "My printer does not work.", goal: "Özür dile ve yardım edeceğini söyle (tek cümle).",
    keywords: [{ w: "sorry", tr: "üzgünüm" }, { w: "help", tr: "yardım" }, { w: "check", tr: "kontrol etmek" }],
    skeleton: "I'm ___ about that. I will ___ the printer.", model: "Sorry about that. I will check the printer now." },
  { id: "s-t02", level: 1, category: "account", subject: "Forgot password", from: { name: "Tom", role: "Sales", country: "UK" },
    body: "I forgot my password.", goal: "Parolayı sıfırlayacağını söyle.",
    keywords: [{ w: "reset", tr: "sıfırlamak" }, { w: "password", tr: "parola" }, { w: "minutes", tr: "dakika" }],
    skeleton: "I will ___ your ___ now.", model: "No problem. I will reset your password in five minutes." },
  { id: "s-t03", level: 1, category: "network", subject: "No internet", from: { name: "Mia", role: "Designer", country: "Netherlands" },
    body: "I have no internet.", goal: "Kısa bir soru sor veya bir adım öner.",
    keywords: [{ w: "wifi", tr: "kablosuz ağ" }, { w: "cable", tr: "kablo" }, { w: "restart", tr: "yeniden başlat" }],
    skeleton: "Please ___ your laptop and ___ the Wi-Fi.", model: "Please restart your laptop and check the Wi-Fi." },
  /* L2: kısa bildirim */
  { id: "s-t04", level: 2, category: "vpn", subject: "VPN does not connect", from: { name: "Lukas", role: "Accountant", country: "Austria" },
    body: "Hello, I am at home. I cannot connect to the VPN. It says error 809. Can you help me?", goal: "Özür dile, bir adım ver, süre söyle.",
    keywords: [{ w: "sorry", tr: "üzgünüm" }, { w: "restart", tr: "yeniden başlat" }, { w: "router", tr: "modem" }, { w: "minutes", tr: "dakika" }],
    skeleton: "Hello, sorry for the ___. Please ___ your router and try again. I will check in ___ minutes.", model: "Hello, sorry for the problem. Please restart your router and try again. I will check again in ten minutes." },
  { id: "s-t05", level: 2, category: "email", subject: "Cannot send email", from: { name: "Sara", role: "Marketing", country: "Spain" },
    body: "Hi, my email stays in the outbox. I tried two times. It is urgent.", goal: "Özür dile, aciliyeti kabul et, bir kontrol öner.",
    keywords: [{ w: "sorry", tr: "üzgünüm" }, { w: "urgent", tr: "acil" }, { w: "outbox", tr: "giden kutusu" }, { w: "check", tr: "kontrol" }],
    skeleton: "Sorry about that. I understand it is ___. Please ___ your internet and open the ___ again.", model: "Sorry about that. I understand it is urgent. Please check your internet and open the outbox again." },
  { id: "s-t06", level: 2, category: "account", subject: "Account locked", from: { name: "Ben", role: "Support", country: "USA" },
    body: "Hello. My account is locked after I typed my password wrong. I need to work now.", goal: "Hesabı açacağını ve ne zaman olacağını söyle.",
    keywords: [{ w: "unlock", tr: "kilidi açmak" }, { w: "account", tr: "hesap" }, { w: "today", tr: "bugün" }, { w: "please", tr: "lütfen" }],
    skeleton: "Hi Ben, I will ___ your account in ___ minutes. Please ___ then.", model: "Hi Ben, I will unlock your account in five minutes. Please try again then." },
  /* L3: adım adım */
  { id: "s-t07", level: 3, category: "network", subject: "Slow internet in meeting room", from: { name: "Clara", role: "Office manager", country: "France" },
    body: "Hello, the internet in the meeting room is very slow. We have a video call with a client at 3 pm. The Wi-Fi shows full signal. Can you fix it before the call?", goal: "Anlayışını göster, 2-3 adım ver, saatten önce haber vereceğini söyle.",
    keywords: [{ w: "understand", tr: "anlıyorum" }, { w: "first", tr: "önce" }, { w: "then", tr: "sonra" }, { w: "before", tr: "önce (zaman)" }, { w: "cable", tr: "kablo" }],
    skeleton: "Hello Clara, I understand it is ___. First, I will ___. Then I will ___. I will ___ you before 3 pm.", model: "Hello Clara, I understand it is important. First, I will check the Wi-Fi access point. Then I will test the speed with a cable. I will update you before 3 pm. Best regards" },
  { id: "s-t08", level: 3, category: "onboarding", subject: "New laptop setup", from: { name: "Daniel", role: "New employee", country: "Poland" },
    body: "Hi, today is my first day. I got a new laptop but I cannot sign in to my email. The paper says I must change my password. How do I do this?", goal: "Selamla, parolayı değiştirme adımlarını sırayla yaz.",
    keywords: [{ w: "welcome", tr: "hoş geldin" }, { w: "first", tr: "önce" }, { w: "click", tr: "tıkla" }, { w: "new password", tr: "yeni parola" }, { w: "then", tr: "sonra" }],
    skeleton: "Hi Daniel, welcome! First, ___ on 'Change password'. Then type your ___ . After that, ___.", model: "Hi Daniel, welcome to the team! First, click on 'Change password'. Then type your new password two times. After that, sign in to your email. Tell me if you need help. Thanks" },
  { id: "s-t09", level: 3, category: "printer", subject: "Printer shows paper jam", from: { name: "Eva", role: "Finance", country: "Sweden" },
    body: "Hello, the printer on the second floor shows a paper jam, but I see no paper inside. I need to print the invoices today.", goal: "Özür dile, adım adım kontrol önerisi ver, alternatif yazıcı söyle.",
    keywords: [{ w: "sorry", tr: "üzgünüm" }, { w: "open", tr: "açmak" }, { w: "tray", tr: "kağıt tepsisi" }, { w: "another", tr: "başka" }, { w: "meanwhile", tr: "bu arada" }],
    skeleton: "Sorry for this. Please ___ the back cover and check the ___. Meanwhile, you can use ___ printer on the first floor.", model: "Sorry for this. Please open the back cover and check the paper tray. Meanwhile, you can use another printer on the first floor. I will come to you in ten minutes. Thanks" },
  /* L4: profesyonel e-posta */
  { id: "s-t10", level: 4, category: "email", subject: "Shared mailbox access", from: { name: "Julia Meyer", role: "Team lead", country: "Germany" },
    body: "Dear IT team, three new members of my team need access to the shared mailbox 'support@company.com'. They start on Monday. Could you please give them access before the weekend and confirm when it is done? Their names are in the attachment. Thank you.", goal: "Resmi bir e-posta yaz: talebi onayla, tarih ver, bilgi eksikse iste.",
    keywords: [{ w: "dear", tr: "sayın" }, { w: "access", tr: "erişim" }, { w: "confirm", tr: "onaylamak" }, { w: "by Friday", tr: "cumaya kadar" }, { w: "regards", tr: "saygılarımla" }],
    skeleton: "Dear Julia, thank you for your ___. I will ___ access to the three users by ___. I will ___ you when it is done. Best regards", model: "Dear Julia, thank you for your request. I will add access to the shared mailbox for the three users by Friday. I will confirm by email when it is done. Please tell me if the names in the attachment change. Best regards" },
  { id: "s-t11", level: 4, category: "network", subject: "Request: guest Wi-Fi for visitors", from: { name: "Peter Novak", role: "Operations manager", country: "Czech Republic" },
    body: "Hello, next Tuesday we will have 12 visitors from a customer. They need internet for 4 hours in the main meeting room. Is it possible to create a temporary guest network? It must be separate from our company network for security reasons.", goal: "Talebi kabul et, güvenlik gerekçesini onayla, süre ve bilgi (şifre) planını yaz.",
    keywords: [{ w: "guest network", tr: "misafir ağı" }, { w: "separate", tr: "ayrı" }, { w: "temporary", tr: "geçici" }, { w: "password", tr: "parola" }, { w: "security", tr: "güvenlik" }],
    skeleton: "Hello Peter, yes, I can ___ a guest network. It will be ___ from the company network for ___. I will send the ___ on Monday.", model: "Hello Peter, yes, I can set up a temporary guest network. It will be separate from the company network for security. I will send the password on Monday and disable it on Tuesday evening. Best regards" },
  { id: "s-t12", level: 4, category: "account", subject: "Suspicious email received", from: { name: "Ayla Demir", role: "HR specialist", country: "Turkey" },
    body: "Hi, I received an email from 'Microsoft Support' that says my account will be closed. It has a link. I did not click it, but I forwarded it to a colleague by mistake. What should I do?", goal: "Sakin ol, tıklamamasını teşekkürle karşıla, bağlantıya basmama, silme ve rapor etme adımlarını yaz.",
    keywords: [{ w: "phishing", tr: "oltalama" }, { w: "do not click", tr: "tıklama" }, { w: "delete", tr: "sil" }, { w: "report", tr: "bildir" }, { w: "colleague", tr: "iş arkadaşı" }],
    skeleton: "Hi Ayla, thank you for ___ us. This looks like a ___ email. Please do not ___ the link. I will ask your ___ to delete it too.", model: "Hi Ayla, thank you for telling us. This looks like a phishing email. Please do not click the link and delete the email. I will also ask your colleague to delete it and report it to security. Best regards" },
  /* L5: escalation, yabancı ekip */
  { id: "s-t13", level: 5, category: "vpn", subject: "URGENT: VPN outage for the Berlin office", from: { name: "Markus Weber", role: "Head of Operations", country: "Germany" },
    body: "Hello, since 08:30 nobody in the Berlin office can connect to the VPN. About 40 people cannot work. We already restarted the router twice. This is the third time this month. Please escalate and tell me when we will have a solution and what you will do to prevent this in the future.", goal: "Özür, durum, kök neden araştırması, tahmini süre ve önleme planı; ton: profesyonel.",
    keywords: [{ w: "apologize", tr: "özür dilemek" }, { w: "root cause", tr: "kök neden" }, { w: "escalate", tr: "üst birime taşımak" }, { w: "update", tr: "güncelleme" }, { w: "prevent", tr: "önlemek" }, { w: "estimate", tr: "tahmin" }],
    skeleton: "Dear Markus, I sincerely ___ for the outage. I have ___ the issue to the network team. Our current ___ is that the VPN gateway ... I will send an ___ every 30 minutes. To ___ this in the future, we will ...", model: "Dear Markus, I sincerely apologize for the outage and the impact on your team. I have escalated the issue to our network team and we are checking the VPN gateway now. Our estimate is a fix within two hours, and I will send you an update every 30 minutes. After the incident, we will find the root cause and share a plan to prevent it. Best regards" },
  { id: "s-t14", level: 5, category: "onboarding", subject: "Request for software installation on 15 laptops", from: { name: "Rachel Green", role: "Project manager", country: "USA" },
    body: "Hi, our new project team of 15 people starts next Monday. We need Visual Studio, Docker and a VPN client on every laptop. Some people are in the US, so please prepare remote installation too. Our budget approval is still pending, but we cannot wait. Can you tell me what you need from me and what the risks are?", goal: "Bilgi iste (onay, lisans), riskleri açıkla, plan ve tarih ver.",
    keywords: [{ w: "approval", tr: "onay" }, { w: "license", tr: "lisans" }, { w: "risk", tr: "risk" }, { w: "remote", tr: "uzaktan" }, { w: "timeline", tr: "zaman çizelgesi" }, { w: "deadline", tr: "son tarih" }],
    skeleton: "Hi Rachel, thank you for the ___. To meet the Monday ___, I need ___ and the ___ for the software. The main ___ is ... I suggest the following ___ : ...", model: "Hi Rachel, thank you for the details. To meet the Monday deadline, I need the budget approval and the license count for the software. The main risk is that remote installation depends on the users being online, so I suggest the following timeline: images ready on Thursday, remote installs on Friday and a check on Monday morning. Please confirm. Best regards" },
  { id: "s-t15", level: 5, category: "network", subject: "Complaint: repeated Wi-Fi problems", from: { name: "Hans Becker", role: "Customer success lead", country: "Switzerland" },
    body: "Dear IT, this is my third message about the Wi-Fi on the 4th floor. Every afternoon the connection drops and my team loses calls with customers. Nobody gives me a clear answer. I need a written plan and an owner, otherwise I will inform the management.", goal: "Özür dile, sorumluluk al, net plan, sahip ve takvim ver; savunmaya geçme.",
    keywords: [{ w: "apologize", tr: "özür dilemek" }, { w: "owner", tr: "sorumlu kişi" }, { w: "plan", tr: "plan" }, { w: "investigate", tr: "araştırmak" }, { w: "by", tr: "-e kadar" }, { w: "update", tr: "güncelleme" }],
    skeleton: "Dear Hans, I apologize for the ___ you had. I am now the ___ for this case. I will ___ the access points today. You will receive a written ___ by ___.", model: "Dear Hans, I apologize for the repeated problems and the lack of a clear answer. I am now the owner of this case. I will investigate the access points on the 4th floor today and check the logs for the afternoon drops. You will receive a written plan by tomorrow noon, and I will send you an update every day until it is fixed. Best regards" }
].map(function (t) { t.date = ""; t.tip = t.tip || ""; return t; });
